name: reelx
description: Reels & Status Downloader.

publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.1
  dio: ^5.5.0+1
  video_player: ^2.9.2
  google_mobile_ads: ^5.2.0
  firebase_messaging: ^15.0.4
  device_info_plus: ^11.2.0
  get_storage: ^2.1.1
  crypto: ^3.0.1
  flutter_local_notifications: ^18.0.1
  video_thumbnail: ^0.5.3
  share_plus: ^10.0.0
  path_provider: ^2.0.9
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.20
  saf: ^1.0.3+4
  permission_handler: ^10.2.0
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rancho
      fonts:
        - asset: assets/fonts/Rancho-Regular.ttf